site_name: ugodoc
site_url: https://ugoproto.github.io/ugodoc/
#repo_url: https://github.com/ugoproto/ugodoc
site_description: A Data Science documentation website.
site_author: Ugo Spark
#site_favicon: favicon.ico
copyright: © Ugo Spark
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
#remote_branch: master
#remote_name: ugodoc

pages:
    - Home: 'index.md'
    - Collection: 'collection.md'
    - Vade Mecum:
        - Edition Cheat Sheets: 'Edition_CS.md'
        - Digital Humanities: 'Digital Humanities.md'
        - Learn Git: 'Learn Git.md'
        - Resources for Data Science: 'Resources for Data Science.md'
        - Storytelling with Data: 'Storytelling with Data.md'
        - 10 Kinds of Stories to Tell with Data: 'Data_Storytelling.md'
        - Infographies: 'Infographies.md'
    - OS & CLI:
        - OS Cheat Sheets: 'OS_CS.md'
        - Codecademy Learn the Command Line Notes: 'Codecademy Learn the Command Line Notes.md'
        - Command Line Crash Course: 'Command Line Crash Course.md'
        - Command Shell Snippets : 'Command Shell Snippets.md'
        - The Linux Command Line: 'The Linux Command Line.md'
        - Ubuntu 16.04: 'Ubuntu.md'
        - Install & Run on Linux: 'Install_tarball.md'
    - SQL & NoSQL:
        - SQL-NoSQL Cheat Sheets: 'SQL-NoSQL_CS.md'
        - Codecademy Learn SQL: 'Codecademy Learn SQL.md'
        - Codecademy SQL, Analyzing Business Metrics: 'Codecademy SQL, Analyzing Business Metrics.md'
        - Codecademy SQL, Table Transformation: 'Codecademy SQL, Table Transformation.md'
        - Introduction to SQL JOINs: 'Introduction to SQL JOINs.md'
    - Web:
        - Web Cheat Sheets: 'Web_CS.md'
        - Build a Website: 'Build a Website.md'
        - HTML and CSS: 'HTML and CSS.md'
        - Markdown & Pandoc: 'Markdown & Pandoc.md'
    - Tests: 'tests.md'

theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

# Build PDF & ePub (only on Readthedocs)
#formats: 
#    - pdf

# Interlinks
# [link](to_other_page.md)
# [link](../relative/page.md)

markdown_extensions:
    - wikilinks # internal links with [[bracketed]]
    - smarty # additional characters
    - subscript
    - superscript
    - nl2br # need a new line to break
    - toc:
        title: CONTENT
        permalink: True
        baselevel: 3
    - footnotes