site_name: ugodoc
site_url: 
repo_url: https://github.com/ugoproto/ugodoc
site_description: A data Science documentation website.
site_author: Ugo Spark
site_favicon: faviconfire.ico
copyright: null
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
remote_branch: gh-pages
remote_name: ugodoc
pages:
    - Home: 'index.md'
    - Collection: 'collection.md'
    - CLI:
        - 'Codecademy Learn the Command Line Notes': 'manuals/Codecademy Learn the Command Line Notes.md'
        - 'Command Line Crash Course': 'manuals/Command Line Crash Course.md'
        - 'Command Shell' : 'manuals/Command Shell.md'
        - 'The Linux Command Line': 'manuals/The Linux Command Line.md'
    - Resources for Data Science:
        - 'Digital Humanities': 'manuals/Digital Humanities.md'
        - 'Learn Git': 'manuals/Learn Git.md'
        - 'Resources for Data Science': 'manuals/Resources for Data Science.md'
        - 'Storytelling with Data': 'manuals/Storytelling with Data.md'
    - SQL.md:
        - 'Codecademy Learn SQL': 'manuals/Codecademy Learn SQL.md'
        - 'Codecademy SQL, Analyzing Business Metrics': 'manuals/Codecademy SQL, Analyzing Business Metrics.md'
        - 'Codecademy SQL, Table Transformation': 'manuals/Codecademy SQL, Table Transformation.md'
        - 'Introduction to SQL JOINs': 'manuals/Introduction to SQL JOINs.md'
    - Web:
       - 'Build a Website': 'manuals/Build a Website.md'
       - 'HTML and CSS': 'manuals/HTML and CSS.md'
    - Tests: 'tests.md'

theme: readthedocs
# Other themes:
    # readthedocs
    # mkdocs

markdown_extensions:
  - wikilinks # internal links with [[bracketed]]
  - smarty # additional characters
#  - subscript
#  - superscript
  - nl2br # new line to break
  - toc:
       title: Content
       permalink: True
       baselevel: 3